### ISSUE TITLE
Importing existing VPS

### ISSUE THREAD

**Issue by seuros** [contabo/terraform-provider-contabo#7]
Hi, 

Is there a way to import the existing resources with terraform import ?

Thanks

**Comment by Maximilian-Temeschinko** [comment]
Hey [seuros](https://github.com/seuros),

It is possible to use the `terraform import` command for VPS. You have to get your `instance_id` for each instance, i.e. VPS you want to import.

example:
```sh
terraform import contabo_instance.my_instance 12345678
```

Please also checkout the terraform docs on this if you haven't already:
[https://www.terraform.io/cli/import](https://www.terraform.io/cli/import)

looks like currently there is no support for generating the config file for us. It will "only" add the instances to the terraform state.

Regards,
Max

**Comment by seuros** [comment]
@Maximilian-Temeschinko , thank you for your reply.

I tried to use the host system as the instance_id. That the correct one ?

```
terraform import contabo_instance.inst 183xx
contabo_instance.inst: Importing from ID "183xx"...
contabo_instance.inst: Import prepared!
  Prepared contabo_instance for import
contabo_instance.inst: Refreshing state... [id=183xx]
╷
│ Error: API error, status code: 404
│ 
│ API error, status code: 404, details: Entry Instances not found by instanceId = 183xx
╵
```

**Comment by Maximilian-Temeschinko** [comment]
The `id` field in terraform for `contabo_instance` is the `instanceId` of the instance resource in the API response.
[https://api.contabo.com/#tag/Instances/operation/retrieveInstance](https://api.contabo.com/#tag/Instances/operation/retrieveInstance).

Option 1:
In order to call the Contabo API you can follow the instructions at [https://api.contabo.com/#section/Introduction/Getting-Started](https://api.contabo.com/#section/Introduction/Getting-Started). And then make a GET request to https://api.contabo.com/v1/compute/instances where you get the list of your instances.

Option 2:
Or use the cli tool `cntb` [https://github.com/contabo/cntb#contabo-command-line-interface-cli](https://github.com/contabo/cntb#contabo-command-line-interface-cli).

if you have the cli-tool installed and configured, you can use the command:
```sh
cntb get instances
```

and the first column INSTANCEID will be the id you need to provide to `terraform import contabo_instance`

hope that helps
Max

**Comment by seuros** [comment]
That was perfect.
